# site settings
title:              Trick hub IDN
subtitle:           "The story of a life"
email:              "trickhubidn@gmail.com"
header-img:         img/home-bg.jpg
description:        "A Blog Theme by Start Bootstrap"
author:             Habibur Rahaman 
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://trickhubidn.github.io"

# Social Profiles
twitter_username:   trickhubindia
github_username:    trickhubindia
facebook_username:  trickhubindia
instagram_username:  trickhubindia
linkedin_username:  trickhubindia

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
